# -*- coding: utf-8 -*-
"""Email slicer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mxq5WWz-eu2uAwlbVCj14sKXPGarfD25
"""

# Prompt the user to enter their email address
email = input("Enter your email address: ")

# Slice the email address to extract the username and domain name
username = email[:email.index("@")]
domain = email[email.index("@")+1:]

# Print the username and domain name
print("Username: ", username)
print("Domain: ", domain)